# this scratch pad does two things.  

# graphs ----
## First, its a quick test of how the graphs would look like when comparing the confidence intervals of the raw estimates with the existing graphs

df <- read.csv("../Carle Strub Estimates/RBoutput_allspp_maincomp_CS.csv")
library(ggplot2)
str(df)

# the problem with this plot is that I have no idea how the variances were generated
allspp_plot <-
  ggplot(df, aes(Year, stand.trad.species.biomass.contributions)) + 
  theme_bw() + 
  geom_point(position=position_dodge(0.5)) + 
  facet_grid(Station~Species) +
  theme(axis.text.x  = element_text(angle=90, vjust=0.2, size=8)) +
  ylab("Biomass Estimate (grams/100 sq. meters)") + xlab("Year") +
  geom_errorbar(aes(ymax=ucl.stand.trad.species.biomass.contributions
, ymin=lcl.stand.trad.species.biomass.contributions
), linewidth=1, width=0.25) +
  theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank())

allspp_plot


# data sets - origin ----
# where did the compensation:main data sets come from
amec.efishing8("../data/RB_year/RoseBlancheAug2000bytypecombinednoeels")
## the above line perfectly matches the biomass of the same year for the below 
RB_salmonids_maincomp

# Delta Method ----
## one site ----
## see Powell2007 The Condor for reference
# estimate - run this to get the estimates for below
## this is where I figured out how to do this but the full Delta Method for all sites is from Pamehac scratch_pad.R and pasted below.
#amec.efishing8("../data/RB_year/RoseBlancheAug2000bysite")


# create a new name to simplify the data manipulatoin and subset by BT
df1 <- RB_carlestrub_output_each_spp_by_site
bt1 <- df1[df1$Species == "BT" &df1$Year == 2000,]

library(dplyr)
library(magrittr)

# just trying to get summaries Kristin's way for one year and species.  Then, I want to use the delta method - this creates the data set to compare with Kristin's approach
bt1_sum <- bt1 |>
  group_by(Type) |>
  summarise(mean = mean(biomass_cs), VAR = var(biomass_cs), SD = sd(biomass_cs))

bt1_sum$Length <- NA  
bt1_sum[bt1_sum$Type == "Compensation", "Length"] <- nrow(bt1[bt1$Type == "Compensation", ])
bt1_sum[bt1_sum$Type == "Main Stem", "Length"] <- nrow(bt1[bt1$Type == "Main Stem", ])

bt1_sum$SE <- bt1_sum$SD/sqrt(bt1_sum$Length)
bt1_sum$dm_var <- NA
bt1_sum$dm_se <- NA


# so this matches Kristin's work - see "RB_Spp_Biomass_cs" in RB_data.R - return to this below

# bring in the upper and lower confidence limits as generated by the AMEC functions run above: this is generally in a file called e.fishing.summary.data.csv but this can easily be overwritten.  To get the below, just run the above code from AMEC.  The point estimates by site are in column L "stand.species.biomass.contr", and the upper/lower CIs are in M/N "stand.species.biomass.contr.ucl"/"stand.species.biomass.contr.lcl".  I just copied them in as stands
# these are from RB_carlestrub_output_each_spp_by_site.xlsx querried for BT and 2000

ul <- c(29.34209877,
        41.22381603,
        98.40297758,
        118.9418596,
        111.7103591,
        326.3486124,
        237.0830874,
        0,
        0,
        0
)
ll  <- c(25.26965585,
         36.91508753,
         80.56261893,
         114.2136129,
         105.0887328,
         314.937459,
         183.5457046,
         0,
         0,
         0
)
temp <- as.data.frame(cbind(ul, ll))
bt1 <- cbind(bt1, temp)

# get the variance estimate for each station
bt1$var <- ((bt1$ul - bt1$biomass_cs)/1.96)^2

# now, need to delta method the SE...need to do this before proceeding
## take the partial derivatives for each row in the full data set and sum them up.  
bt1$pd <- NA
# sum the Compensation sites divided by square of number of sites, i.e, partial derivatives
bt1$pd[1:bt1_sum$Length[1]] <- 
  bt1$var[1:bt1_sum$Length[1]]/(bt1_sum$Length[1])^2 # partial derivative - see Powell 2007 Condor
bt1$pd[(bt1_sum$Length[1] + 1):nrow(bt1)] <- 
  bt1$var[(bt1_sum$Length[1] + 1):nrow(bt1)]/(bt1_sum$Length[2])^2 #
bt1$pdVar <- bt1$var*bt1$pd 
dm_var <- rep(NA, 2)
dm_var[1] <- sum(bt1$pdVar[1:bt1_sum$Length[1]]) # so this should be the variance
dm_var[2] <- sum(bt1$pdVar[(bt1_sum$Length[1] + 1):nrow(bt1)])
dm_se <- sqrt(dm_var)

# add these to the output Kristin produced for comparison 
bt1_sum[bt1_sum$Type == "Compensation", "dm_var"] <- dm_var[1]
bt1_sum[bt1_sum$Type == "Compensation", "dm_se"] <- dm_se[1]
bt1_sum[bt1_sum$Type == "Main Stem", "dm_var"] <- dm_var[2]
bt1_sum[bt1_sum$Type == "Main Stem", "dm_se"] <- dm_se[2]

bt1_sum$ucl <- bt1_sum$mean + 1.96*bt1_sum$dm_se
bt1_sum$ull <- bt1_sum$mean - 1.96*bt1_sum$dm_se
mean(bt1$biomass_cs[1:7])




## DM - full ----
dfb <- RB_carlestrub_output_each_spp_by_site_all[, c(1:4, 12:14, 27)]
dfb <- rename(dfb, bm = stand.species.biomass.contr,
              bm_ucl = stand.species.biomass.contr.ucl,
              bm_lcl = stand.species.biomass.contr.lcl)
str(dfb)

dfb[dfb$Species == "AS" & dfb$Year == 2002,]

# dft - dataframe for transition
dft <- dfb |>
  group_by(Species, Year, Type) |>
  mutate(bm_var = ((bm_ucl - bm)/1.96)^2, 
         bm_sd = sqrt(bm_var),
         bm_se = sqrt(bm_var)/length(Station),
         #bm_sd1 = (bm_ucl - bm)/1.96, # gives the same result as bm_sd
         n = length(Station),
         pd = bm_var/length(Station)^2,
         pdVar = bm_var*pd 
  )

# add a Before/After variable
# dft$time <- NA
# for(i in seq_along(dft$Year)){
#   if(dft$Year[i] == 1990){
#     dft$time[i] <- "Before"
#   } else {
#     dft$time[i] <- "After"
#   }
# }
str(dft, give.attr=FALSE)




## dfd - dataframe for delta method
dfd <- dft |>
  group_by(Species, Year, Type) |>
  summarise(mean = mean(bm),
            VAR = sum(pdVar), 
            ll = mean - 1.96*(sqrt(VAR)/length(Type)),
            ul = mean + 1.96*(sqrt(VAR)/length(Type))
  )
dfd
#View(dfd)
str(dfd, give.attr=FALSE)

# this matches previous graphs like RB_SPP_Biomass_cs ito point estimates but obviously, the CIs are much smaller.
ggplot(dfd, aes(as.factor(Year), mean, colour=Type)) + 
  geom_point(size=3, position=position_dodge(0.5)) +
  theme_bw() +  
  theme(axis.text.x  = element_text(vjust=0.2, size=12)) +
  ylab("Biomass Estimate  (grams/100 sq. meters)") + xlab("Year") +
  theme(legend.title=element_blank()) +
  theme(legend.position=c(.88, .88)) +
  geom_errorbar(aes(ymax=ul, ymin=ll), linewidth=1, width=0.25, position=position_dodge(0.5)) +
  geom_hline(yintercept = 0) +
  facet_grid(Type~Species) + 
  theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank())

# tabulate ----
# this is to tabulate the number of fish per pass by year and species


df_tab <- RB_carlestrub_output_each_spp_by_site_all[, c(1:5)]
str(df_tab)

library(tidyr)
df_tab |>
  select(Species, Year, Station, biomass.caught) |>
pivot_wider(names_from = Station, values_from = biomass.caught) |>
  arrange(Species) |>
  print(n = Inf)




df_abun <- RB_carlestrub_output_each_spp_by_site_all[, c(1:4, 8)]
str(df_abun)

df_abun[df_abun$Species != "EEL",]

library(tidyr)
df_tab1 <- df_abun[df_abun$Species != "EEL",] |>
  select(Species, Year, Station, abundance.caught) |>
  pivot_wider(names_from = Station, values_from = abundance.caught) |>
  arrange(Species) |>
  print(n = Inf)

sum(is.na(df_tab1))/(10*16)

temp <- subset(df_abun, abundance.caught < 10)
length(temp$abundance.caught)

df_abun[df_abun$abundance.caught >= 30 & !is.na(df_abun$abundance.caught), ]


# now, to look at the variances

str(dft, give.attr = F)
df_tab2 <- dft |> 
  ungroup() |>
  select(Species, Year, Station, bm_var) |>
  pivot_wider(names_from = Station, values_from = bm_var) |>
  arrange(Species) |>
  print(n = Inf)

sum(is.na(df_tab2))/(10*16)

length(df_tab2[df_tab2 == 0])

length(dft$bm_var[dft$bm_var > 100 & !is.na(dft$bm_var)]) # length >10 = 30, >50 = 13, >100 = 9


# now, looking at abundance
df_abun[df_abun$abundance.caught >= 30 & !is.na(df_abun$abundance.caught), ]
length(df_abun$abundance.caught[df_abun$abundance.caught <= 5 & !is.na(df_abun$abundance.caught)])/(10*16) # > 30 = 7, > 20 = 16, > 10 = 34, > 5 = 0.56 - so proportions aren't that much different BUT
sum(is.na(df_abun$abundance.caught))/(10*16) # lots of sites with NAs - no fish


# trying to download RB data from gbd file

sf::st_read(dsn = "../RoseBlanche_wpts_2015.gdb")
# END ----