# this scratch pad does two things.  

# graphs ----
## First, its a quick test of how the graphs would look like when comparing the confidence intervals of the raw estimates with the existing graphs

df <- read.csv("../Carle Strub Estimates/RBoutput_allspp_maincomp_CS.csv")
library(ggplot2)
str(df)

# the problem with this plot is that I have no idea how the variances were generated
allspp_plot <-
  ggplot(df, aes(Year, stand.trad.species.biomass.contributions)) + 
  theme_bw() + 
  geom_point(position=position_dodge(0.5)) + 
  facet_grid(Station~Species) +
  theme(axis.text.x  = element_text(angle=90, vjust=0.2, size=8)) +
  ylab("Biomass Estimate (grams/100 sq. meters)") + xlab("Year") +
  geom_errorbar(aes(ymax=ucl.stand.trad.species.biomass.contributions
, ymin=lcl.stand.trad.species.biomass.contributions
), linewidth=1, width=0.25) +
  theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank())

allspp_plot


# Delta Method ----
## see Powell2007 The Condor for reference
# estimate - run this to get the estimates for below
amec.efishing8("../data/RB_year/RoseBlancheAug2000bysite")


# create a new name to simplify the data manipulatoin and subset by BT
df1 <- RB_carlestrub_output_each_spp_by_site
bt1 <- df1[df1$Species == "BT" &df1$Year == 2000,]

library(dplyr)
library(magrittr)

# just trying to get summaries Kristin's way for one year and species.  Then, I want to use the delta method
bt1_sum <- bt1 |>
  group_by(Type) |>
  summarise(mean = mean(biomass_cs), VAR = var(biomass_cs), SD = sd(biomass_cs))

bt1_sum$Length <- NA  
bt1_sum[bt1_sum$Type == "Compensation", "Length"] <- nrow(bt1[bt1$Type == "Compensation", ])
bt1_sum[bt1_sum$Type == "Main", "Length"] <- nrow(bt1[bt1$Type == "Main", ])

bt1_sum$SE <- bt1_sum$SD/sqrt(bt1_sum$Length)

# so this matches Kristin's work - see "RB_Spp_Biomass_cs" in RB_data.R - return to this below

# bring in the upper and lower confidence limits as generated by the AMEC functions run above: this is generally in a file called e.fishing.summary.data.csv but this can easily be overwritten.  To get the below, just run the above code from AMEC.  The point estimates by site are in column L "stand.species.biomass.contr", and the upper/lower CIs are in M/N "stand.species.biomass.contr.ucl"/"stand.species.biomass.contr.lcl".  I just copied them in as stands

ul <- c(29.34209877,
        41.22381603,
        98.40297758,
        118.9418596,
        111.7103591,
        326.3486124,
        237.0830874,
        0,0,0)
ll  <- c(25.26965585,
         36.91508753,
         80.56261893,
         114.2136129,
         105.0887328,
         314.937459,
         183.5457046,
         0,0,0)
temp <- as.data.frame(cbind(ul, ll))
bt1 <- cbind(bt1, temp)

# get the variance estimate for each station
bt1$var <- ((bt1$ul - bt1$biomass_cs)/1.96)^2
bt1_sum$dm_var <- NA
bt1_sum$dm_se <- NA

# now, need to delta method the SE...need to do this before proceeding
## take the partial derivatives in each row - sum them up.  
bt1$pd <- bt1$var/(bt1_sum$Length[1])^2
bt1$pdVar <- bt1$var*bt1$pd 
dm_var <- sum(bt1$pdVar) # so this should be the variance
dm_se <- sqrt(dm_var)

# add these to the output Kristin produced for comparison 
bt1_sum[bt1_sum$Type == "Compensation", "dm_var"] <- dm_var
bt1_sum[bt1_sum$Type == "Compensation", "dm_se"] <- dm_se
bt1_sum$ucl <- bt1_sum$mean + 1.96*bt1_sum$dm_se
bt1_sum$ull <- bt1_sum$mean - 1.96*bt1_sum$dm_se
mean(bt1$biomass_cs[1:7])


# data sets - origin ----
# where did the compensation:main data sets come from
amec.efishing8("../data/RB_year/RoseBlancheAug2000bytypecombinednoeels")
## the above line perfectly matches the biomass of the same year for the below 
RB_salmonids_maincomp

